### ISSUE TITLE
Use JSON output for the PHPCS report

### ISSUE THREAD

**Issue by grappler** [ernilambar/ns-theme-check#1]
Instead of using the standard output which does not look that great, we could use the JSON output from PHPCS and create our own output layout with a bit of HTML to make it easier to read.

To get the JSON output you need to define the report as JSON e.g. `$values['report'] = 'json'`

**Comment by ernilambar** [comment]
Ok, I will work on that.

**Comment by ernilambar** [comment]
Fixed https://github.com/ernilambar/ns-theme-check/pull/3
