### ISSUE TITLE
Upload on org directory

### ISSUE THREAD

**Issue by rinkuyadav999** [ernilambar/ns-theme-check#14]
Seems it should be on w.org plugin directory so we can automatically update. (may be temporary)

**Comment by dingo-d** [comment]
Don't know. WPTRT coding standards are still in works. And I have a feeling that it might take some time for them to be near completion (should ask @grappler or @jrfnl who have more info on that). So it would have to be updated every once in a while.

Once they are official (on handbook pages) then it would make sense to release it on .org imo

**Comment by grappler** [comment]
My personal goal is get the Theme Check ready for use in Production by June this year.

There are a few things that PHPCS cannot check for and we need to create a separate solution that we will integrate in the theme check. We need to see how we get on with this separate solution. If we do not make sufficient progress we may just have to remove the checks from the official Theme Check and merge the two plugins. 

The way I see this plugin is a beta version of Theme Check plugin. The code from here will be moved to the official plugin.

I don't think we will be having many more updates of the plugin. There a few new features coming to this plugin and a few more checks in the next few weeks.

If it is uploaded to WordPress.org it should be marked as the beta version.

**Comment by ernilambar** [comment]
I dont think we need to upload this plugin in directory. This plugin is just for testing sniffs and there will be more advanced separate Theme Check plugin in the future. Moreover, as this plugin is generally for dev purpose, manually updating plugin wont be too difficult  for dev person. :smile:
