### ISSUE TITLE
Uncaught PHP_CodeSniffer_Exception

### ISSUE THREAD

**Issue by dingo-d** [ernilambar/ns-theme-check#20]
First I installed the zip file, but couldn't get the new options to work. Then I doenloaded the git files and pasted over the downloaded zip and got the new options to show (yay!) but then got 

~~~
Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "PHPCompatibility" does not exist in /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167
Stack trace:
#0 /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/vendor/squizlabs/php_codesniffer/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/srv/www/wordpr...', 0)
#1 /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/vendor/squizlabs/php_codesniffer/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/srv/www/wordpr...')
#2 /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/inc/helpers.php(225): PHP_CodeSniffer_CLI->process(Array)
#4 /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/inc/helpers.php(148): ns_theme_check_do_sniff('piclectic', Arr in /srv/www/wordpress-default/wp-content/plugins/ns-theme-check/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1167
~~~

error :(

What did I do wrong? (besides just pasting things over xD)

**Comment by ernilambar** [comment]
Did you downloaded correct zip? https://github.com/ernilambar/ns-theme-check#option-1-easy

**Comment by ernilambar** [comment]
Another thing is that master is not the production version. Tagged version should be used. PHP Comapt library is integrated in master but not released yet.

**Comment by ernilambar** [comment]
If you want to live in edge you should follow these steps :smile: https://github.com/ernilambar/ns-theme-check#option-2-nerdy

**Comment by dingo-d** [comment]
Yeah, first I got the 0.1.2 zip file, and it was weird that I couldn't select more options, so I tried just overwriting it with the files from the master :D I'll try with the nerdy option :D

**Comment by dingo-d** [comment]
Tried installing with composer, as admin, got this:

~~~
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing squizlabs/php_codesniffer (2.8.0)
    Downloading: 100%

  - Installing wimg/php-compatibility (7.1.1)
    Downloading: 100%

  - Installing wp-coding-standards/wpcs (dev-feature/theme-review-sniffs a62457e)
    Cloning a62457e33c9b415ed773b85005f62e4e57810756 from cache

Generating autoload files
> rm -rf vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility; cp -rp vendor/wimg/php-compatibility vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility
rm: unknown option -- p
Try 'rm --help' for more information.
Script rm -rf vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility; cp -rp vendor/wimg/php-compatibility vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility handling the post-install-cmd event returned with error code 1
~~~

any idea what this might be?

**Comment by ernilambar** [comment]
@grappler may have better idea on this.

**Comment by grappler** [comment]
@dingo-d What operating system are you running this on?

**Comment by dingo-d** [comment]
Windows 10. I also have php up and running with composer and node installed.

**Comment by grappler** [comment]
Ok, the command `rm` does not work on Windows. For now you can use this ZIP file till we make a new update.
[ns-theme-check.zip](https://github.com/ernilambar/ns-theme-check/files/779590/ns-theme-check.zip)

**Comment by dingo-d** [comment]
Thanks! I'll try it when I get home :)

**Comment by dingo-d** [comment]
Works like a charm! Thanks @grappler!

**Comment by dingo-d** [comment]
I found a workaround for this one on Windows 10.

You can use [Bash on Ubuntu on Windows ](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/). If your local installation (if you're using [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) like I am) is on another drive, you can [easily change to it](https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/). Then you'll need to `apt-get` composer, git and npm. 

And then you can follow the [nerdy rules](https://github.com/ernilambar/ns-theme-check#option-2-nerdy) to install the plugin, and you'll have the latest one ready to use :)

**Comment by pattonwebz** [comment]
Was seeing this same issue, grabbing from master instead of relying on the rules in releases fixed for me too.

P.S. `del` is the Windows equivalent of `rm`.
