### ISSUE TITLE
Wrong ERROR Notice: Please spell "WordPress" correctly. Found 1 misspelling(s): wordpress

### ISSUE THREAD

**Issue by codersantosh** [ernilambar/ns-theme-check#200]
I found this notice for this code:
`get_the_author_meta('wordpress');`

I believe this will the same for 
`the_author_meta('wordpress');`

or other similar functions.

**Comment by dingo-d** [comment]
This looks like an upstream issue (WPCS). Not directly related to Theme Sniffer 🙂 

You can search the https://github.com/WordPress/WordPress-Coding-Standards/ for this, and report the issue there.

**Comment by codersantosh** [comment]
Got you! Thanks 🙂
