### ISSUE TITLE
Dir error plugin is not activating 

### ISSUE THREAD

**Issue by wparslan** [ernilambar/ns-theme-check#211]
**Describe the bug**

**To Reproduce**
1. It is not even activating.

**Expected behavior**
Plugin to activate.

**Screenshots**
![image](https://user-images.githubusercontent.com/66727492/103451567-45f87800-4ce7-11eb-9448-bc2c57a2f22f.png)

**Environment (please complete the following information):**
 - OS: [Windows10]
 - Browser [Edge, chrome, safari]
 - PHP Version [7.4.1, 7.3.5]
 - WP Version [5.6]

**Additional context**
Dir is missing or changed completely, resolve immediately

**Comment by larrach** [comment]
HI,

I think I have same issue when I try to activate the plugin

The BO message error is 
`
Fatal error: Uncaught Error: Class 'Theme_Sniffer\Core\Plugin_Factory' not found in /wp-content/plugins/theme-sniffer-development/theme-sniffer.php:58 Stack trace: #0 /wp-admin/includes/plugin.php(2300): include() #1 /wp-admin/plugins.php(191): plugin_sandbox_scrape('theme-sniffer-d...') #2 {main} thrown in /wp-content/plugins/theme-sniffer-development/theme-sniffer.php on line 58`


 
**Environment**
-    OS: [macOS Mojave]
-    Browser [Firefox]
-    PHP Version [7.3.27]
-    WP Version [5.7]

**Comment by dingo-d** [comment]
Are you installing it from the repository or via zip? If you are installing it by just downloading or cloning the repo, you'll need to build it as well.

**Comment by wparslan** [comment]
@larrach please use this [plugin's version](https://github.com/WPTT/theme-sniffer/releases/download/1.1.2/theme-sniffer.zip), it is provided in the description of this very Github Repo.

**Comment by larrach** [comment]
@dingo-d , @wparslan  .
You 're right, It works nows. 
thanks a lot

**Comment by wparslan** [comment]
Closing the thread
