### ISSUE TITLE
Fatal error: Uncaught Error: Class "Theme_Sniffer\Core\Plugin_Factory" not found

### ISSUE THREAD

**Issue by mrmolaei** [ernilambar/ns-theme-check#223]
Hi, I am trying to activate the plugin but it has a problem:

` Fatal error: Uncaught Error: Class "Theme_Sniffer\Core\Plugin_Factory" not found in C:\Users\Lion\Local Sites\wptest\app\public\wp-content\plugins\theme-sniffer-development\theme-sniffer.php on line 58`

WordPress: 5.8
PHP: 7.3.5 - 8.0.0 (Tested on several version)

**Comment by dingo-d** [comment]
If you've just downloaded the zip from the GH you'll need to bundle it as described in the readme. Otherwise use the [release zip](https://github.com/WPTT/theme-sniffer/releases/download/1.1.2/theme-sniffer.zip)
