### ISSUE TITLE
[New Feature] Replace shell_exec with eval

### ISSUE THREAD

**Issue by erikdemarco** [ernilambar/ns-theme-check#229]
I got this error "Theme Sniffer requires shell_exec to be enabled to function" Because my server disable shell_exec, and most other also do.
Is it possible to replace shell_exec with eval? because eval cant be disabled by all host because its not a function

**Comment by dingo-d** [comment]
Hi!

You shouldn't run theme sniffer on production or any live server tbh.

It's intended to be run locally when developing a theme. And it's not possible to replace shell_exec with eval, because phpcs itself is using it, so without it, you cannot run it.
