### ISSUE TITLE
Improve output styling

### ISSUE THREAD

**Issue by grappler** [ernilambar/ns-theme-check#23]
Following what @jrfnl documented with the [xsl templates](https://github.com/jrfnl/make-phpcs-work-for-you/tree/master/xsl-template) I was able to create this screenshot. I think we can use this as inspiration to improve our layout.

![image](https://cloud.githubusercontent.com/assets/1785641/23054921/04a9735a-f4e3-11e6-8ffd-51838753f316.png)

**Comment by ernilambar** [comment]
I have add some styling for report in https://github.com/ernilambar/ns-theme-check/pull/25 It looks much better now :smile:

**Comment by ernilambar** [comment]
Fixed in https://github.com/ernilambar/ns-theme-check/pull/25
