### ISSUE TITLE
HTML outputted in the report

### ISSUE THREAD

**Issue by dingo-d** [ernilambar/ns-theme-check#4]
I found an error when showing the report while sniffing. I am not sure how are you bundling the sniffer in the plugin (manually?) I didn't look that much in the code, but it seems to me that the full report file is missing (on line 182 in `\Reports\Full.php`)

~~~php
echo htmlspecialchars($errorMsg, ENT_QUOTES, 'UTF-8', false).PHP_EOL;
~~~

I tried to make a PR to the phpcs, but the author explained that this is a human readable format and that it should remain that way, and that the better course of action would be to use

> JSON, XML or CSV report types and then display the output however you want.

The reason for this issue is that the report, as it currently is, will render the HTML elements in the report. For instance (on the left is the plugin, on the right the report I manually made with phpcs):

![issue_1](https://cloud.githubusercontent.com/assets/8638515/22173222/73012ad2-dfbc-11e6-9410-6aaf5bdc90f8.png)

When corrected would be

![issue_1_corrected](https://cloud.githubusercontent.com/assets/8638515/22173224/7cbd8a70-dfbc-11e6-9738-ca9a3117ec0a.png)

I tried adding `htmlspecialchars` in the `helpers.php` of the plugin but that didn't work. You could change the report to JSON, then parse it and show it I guess, don't know how much time that would take. Or, if you are manually placing codesniffer in you can modify the file I did, even though this will only create issues if you need to update the code sniffer periodically.

**Comment by grappler** [comment]
Related issues https://github.com/ernilambar/ns-theme-check/issues/1 & https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/749
