### ISSUE TITLE
Fatal Error: Autoload.php

### ISSUE THREAD

**Issue by rohitink** [ernilambar/ns-theme-check#5]
Warning: require_once(/Users/Rohit/...../wp-content/plugins/ns-theme-check-master/vendor/autoload.php): failed to open stream: No such file or directory in /Users/Rohit/Documents/Sites/Test/wp-content/plugins/ns-theme-check-master/inc/helpers.php on line 105

Fatal error: require_once(): Failed opening required '/Users/Rohit/......./wp-content/plugins/ns-theme-check-master/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Users/Rohit/...../wp-content/plugins/ns-theme-check-master/inc/helpers.php on line 105

Any Ideas?

**Comment by ernilambar** [comment]
Bundled distribution zip file should be used rather than download custom zip from GH.
