### ISSUE TITLE
Start checking for PHP compatibility.

### ISSUE THREAD

**Issue by grappler** [ernilambar/ns-theme-check#9]
To do so we would use this PHPCS addon https://github.com/wimg/PHPCompatibility

We can define the versions that are check with this.
`PHP_CodeSniffer::setConfigData( 'testVersion', '5.2-7.0', true );`

The best way to implement it is to be able to define the lowest supported PHP version by the theme.

To set it up dynamically we would have.
```php
$minimum_php = '5.2'
PHP_CodeSniffer::setConfigData( 'testVersion', $minimum_php . '-7.0', true );
```

This mean the maximum supported version cannot be changed as we want people to support PHP7.

**Comment by ernilambar** [comment]
Fixed in https://github.com/ernilambar/ns-theme-check/pull/13
